/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class Clear */

#ifndef _Included_Clear
#define _Included_Clear
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Clear
 * Method:    clsCmd
 * Signature: ()V
 */
	JNIEXPORT void JNICALL Java_Clear_clsCmd
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
